pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'solace-request-reply'
include 'shared-dto'
include 'shared-proto'
include 'solace-library'
include 'server'
include 'client'
