apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: server
build:
  artifacts:
    - image: server
      runtimeType: jvm
      jib:
        project: server
        type: gradle
    - image: client
      runtimeType: jvm
      jib:
        project: client
        type: gradle
manifests:
  rawYaml:
    - server/k8s/deployment.yaml
    - client/k8s/deployment.yaml