server:
  port: 8083

spring:
  cloud:
    function:
      definition: bookingreply
    stream:
      bindings:
        bookingreply-in-0:
          destination: bookingreply
          group: bookingreply-group
          consumer:
            concurrency: 1
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
      solace:
        bindings:
          bookingreply-in-0:
            consumer:
              queueAdditionalSubscriptions: booking/train/reply


solace:
  java:
    host: tcp://localhost:55554
    msgVpn: default
    clientUsername: default
    clientPassword: default


