buildscript {
    dependencies {
        classpath libs.asm.get() // JIB plugin asm version override
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'java'
    alias(libs.plugins.gradleGitProperties)
    alias(libs.plugins.semverGitPlugin)
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyMgmt)
    alias(libs.plugins.jibPlugin)
    alias(libs.plugins.sonarQubePlugin)
}

ext{
    set('hazelcast.version', libs.versions.hazelcastVersion.get())
    set('container_registry', project.findProperty('container_registry'))
}

semver {
    nextVersion = '0.1.0'
    snapshotSuffix = "SNAPSHOT"
    dirtyMarker = "-dirty"
    initialVersion = "0.1.0"
}

group 'cris.prs.msg'
version = semver.info.version

bootJar{
    enabled = true
    launchScript()
}

jar {
    enabled = false
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

dependencyManagement {
    imports {
        mavenBom "${libs.solaceSpringBootBom.get()}"
    }
}

gitProperties {
    extProperty = 'gitProps'
    if(!layout.projectDirectory.dir(".git").asFile.isDirectory()) {
        dotGitDirectory = layout.projectDirectory.dir("../git/modules/${rootProject.name}")
    }
}
generateGitProperties.outputs.upToDateWhen { false }

dependencies {

    annotationProcessor libs.lombok
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    compileOnly libs.lombok
    implementation libs.logbackClassic
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation project(":solace-library")
    implementation libs.javaFaker
    developmentOnly("org.springframework.boot:spring-boot-devtools")
}

test {
    useJUnitPlatform()
}

jib {
    container {
        creationTime = project.provider {project.ext.gitProps['git.commit.time']}
        entrypoint = ["/usr/local/sbin/tini", "--"]
        args = ["supervisord", "-e", "info", "-n", "-l", "/dev/stdout", "-y", "0", "-z", "0"]
    }
    extraDirectories {
        paths {
            path {
                from = file('docker')
                into = '/etc/supervisor/conf.d'
            }
        }
    }

    from {
        image = "${container_registry}/apos/base-images/ubi9/spring-app:jre-24.0.1-v0.1.0@sha256:8738e693608dcddd322ecf5c2732ac7912c7c63d7dd7533498cba8ef527e97f1"
    }

    to {
        image = "${container_registry}/basak.anupam/${project.name.toLowerCase()}"
    }
}