#apiVersion: v1
#kind: Service
#metadata:
#  namespace: anupam
#  name: server
#  labels:
#    app: server
#spec:
#  type: ClusterIP
#  selector:
#    app: server
#  ports:
#    - port: 80
#      targetPort: 8080
#      protocol: TCP
#      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: anupam
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
      annotations:
        openshift.io/required-scc: "apos-application-scc"
    spec:
      containers:
        - name: server
          image: server
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: |
                --add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED 
                --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED 
                --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -XX:+ExitOnOutOfMemoryError
#          ports:
#            - containerPort: 8080
#              name: http
#              protocol: TCP
      imagePullSecrets:
        - name: basak-anupam-pull-secret