server:
  port: 8080

spring:
  config:
    import: configserver:${SPRING_CONFIG_SERVER_URL:http://aposconfigserver.dev1.prs}
  cloud:
    function:
      definition: myReplyConsumer
    stream:
      bindings:
        myReplyConsumer-in-0:
          destination: bkgRep
          group: bkgRepGrp
          consumer:
            concurrency: 10
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://broker-pubsubplus:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
      solace:
        bindings:
          myReplyConsumer-in-0:
            consumer:
              selector: "hostname = '${HOSTNAME}'"
              queueAdditionalSubscriptions:
                - bkgRep/trn

replyTopic: bkgRep/trn

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9090}
  endpoint:
#    env:
#      show-values: ALWAYS
#    configprops:
#      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full