    [program:Application]
    ;user = apos
    command = java %(ENV_JAVA_OPTS)s -cp @/app/jib-classpath-file @/app/jib-main-class-file
    autorestart = true
    stdout_logfile =  /dev/stdout
    stdout_logfile_maxbytes = 0
    redirect_stderr = true
